name: salmon-rnaseq
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # Core tools
  - sra-tools                   # SRA toolkit for downloading sequencing data
  - parallel-fastq-dump         # Download FASTQ files from SRA or ENA repositories. (https://github.com/rvalieris/parallel-fastq-dump)
  - salmon                      # transcript quantification
  - fastqc                      # optional QC
  - multiqc                     # summary reports
  
